In [2]:
# -*- coding: utf-8 -*-


import numpy
from functools import reduce
from operator import mul


def matrix_mul(A, B):
    A_m = numpy.matrix(A)
    B_m = numpy.matrix(B)
    return (A_m*B_m).tolist()


def rezzad1():
    A = numpy.random.randint(0, 100, (3, 5))
    B = numpy.random.randint(0, 100, (5, 2))
    print('A = {}\nB = {}\nA * B = {}'.format(A, B, matrix_mul(A, B)))


def rezzad2():
    A = numpy.random.randint(0, 100, (5, 3))
    B = numpy.random.randint(0, 100, (3, 1))
    print('A = {}\nB = {}\nA * B = {}'.format(A, B, matrix_mul(A, B)))


def rezzad3():
    n = numpy.random.randint(0, 100)
    A = numpy.random.randint(0, 100, (n, n))
    B = numpy.random.randint(0, 100, (n))
    X = numpy.linalg.solve(A, B)
    print('A = {}\n A * X = {}\nX = {}'.format(A, B, X))


def rezzad4():
    n = numpy.random.randint(1, 100)
    A = numpy.matrix(numpy.random.randint(0, 100, (n, n)))
    print('A = {}\ndet(A) = {}'.format(A, numpy.linalg.det(A)))


def rezzad5():
    n = numpy.random.randint(3, 4)
    A = numpy.matrix(numpy.random.randint(0, 100, (n, n)))
    print('A = {}\nA^-1 = {}\nA^T = {}'.format(A,
                                               numpy.linalg.inv(A),
                                               numpy.transpose(A)))


def _addition():
    not_equal_counter = 0
    iter_count = 1000
    for i in range(iter_count):
        A = numpy.matrix(numpy.random.randint(0, 100, (5, 5)))
        det = numpy.round(numpy.linalg.det(A))
        eigvals = numpy.round(reduce(mul, numpy.linalg.eigvals(A)))
        if not numpy.equal(det,
                           eigvals):
            print('Not equal with det = {} and eigvals = {}'
                  .format(det, eigvals))
            not_equal_counter += 1
    print('Не было равно {} из {} раз'.format(not_equal_counter,
                                                iter_count))


rezzad1()
rezzad2()
rezzad3()
rezzad4()
rezzad5()
_addition()

A = [[95  6 16 18 71]
 [55 86 51 37 37]
 [ 4 21 14 97 31]]
B = [[24 26]
 [ 1  4]
 [65 80]
 [75 38]
 [38 21]]
A * B = [[7374, 5949], [8902, 8037], [9480, 5645]]
A = [[ 7 51 94]
 [44 19  1]
 [ 9 14 69]
 [42 50 27]
 [55  2 76]]
B = [[92]
 [90]
 [22]]
A * B = [[7302], [5780], [3606], [8958], [6912]]
A = [[57]]
 A * X = [24]
X = [0.42105263]
A = [[ 5 59 27 ... 62 96 13]
 [27 77 70 ... 37 13 53]
 [61 38  3 ... 70 21 10]
 ...
 [96 18 54 ... 36 81  3]
 [18 89 92 ...  9 75 52]
 [42 15 81 ... 95 21  5]]
det(A) = -3.0527471689746213e+182
A = [[17 61 40]
 [ 1 58 78]
 [34 89 84]]
A^-1 = [[-0.0448654  -0.03389831  0.05284148]
 [ 0.05565911  0.00147384 -0.0278729 ]
 [-0.04081235  0.01215917  0.02004855]]
A^T = [[17  1 34]
 [61 58 89]
 [40 78 84]]
Не было равно 0 из 1000 раз
